# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: openjdk:12-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
    
      - run: git clone https://github.com/GrupoTorax/Commons.git ../Commons
      
      - run: git clone https://github.com/GrupoTorax/ExamsIO.git ../ExamsIO
      
      - run: git clone https://github.com/GrupoTorax/PDI.git ../PDI
      
      - run: git clone https://github.com/Jouwee/RxSling.git ../RxSling
     
      - run: mvn install:install-file -Dfile=../ExamsIO/lib/pixelmed.jar -DgroupId=com.pixelmed -DartifactId=pixelmed -Dversion=1.0 -Dpackaging=jar
      
      - run: mvn -f ../Commons/pom.xml install

      - run: mvn -f ../ExamsIO/pom.xml install
      
      - run: mvn -f ../PDI/pom.xml install    
      
      - run: mvn -f ../RxSling/pom.xml install    
    
      - checkout

      # run tests!
      - run: mvn integration-test


